#!/bin/sh
# Prepend a JIRA ticket ID from the branch name to the commit message
BRANCH_NAME=$(git branch | grep -o '^*\s[A-Za-z]*-[0-9]*' | sed 's/* //')
ORIGINAL_COMMIT_MESSAGE=$(cat $1)

if [ -z "$BRANCH_NAME" ]
then
    echo "$ORIGINAL_COMMIT_MESSAGE" > "$1"
else
    echo "[$BRANCH_NAME] $ORIGINAL_COMMIT_MESSAGE" > "$1"
fi
